#!/bin/sh

adduser \
  --quiet \
  --system \
  --home /opt/geosearch \
  --no-create-home \
  --shell /bin/bash \
  --group \
  --gecos "MyGov Geo-Search Service" \
  geosearch

mkdir -p /var/log/geosearch
chmod 755 /var/log/geosearch
chown geosearch:nogroup /var/log/geosearch

service geosearch start
