#!/bin/sh

adduser \
  --quiet \
  --system \
  --home /opt/geosearch \
  --no-create-home \
  --shell /bin/bash \
  --group \
  --gecos "MyGov Geo-Search Service" \
  geosearch

systemctl daemon-reload
systemctl enable geosearch
systemctl start geosearch
